version: '2'

networks:
  finance:

services:

  ca_tcib:
    hostname: ca.tcib
    image: hyperledger/fabric-ca:1.4.6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-tcib
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.tcib-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e28d99b82db3152dd3a7d08d6330930a31792d63d2b340b18bf65f2804fff97a_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.tcib-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e28d99b82db3152dd3a7d08d6330930a31792d63d2b340b18bf65f2804fff97a_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b tcibadmin:tcibpw -d'
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/tcib/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - finance


  ordererorg-orderer-ordererorg:
    hostname: ordererorg-orderer-ordererorg
    image: hyperledger/fabric-orderer:1.4.6
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./artifacts:/etc/hyperledger/configtx
        - ./artifacts/crypto-config/ordererOrganizations/finance.com/orderers/ordererorg-orderer-ordererorg.finance.com/:/etc/hyperledger/crypto/orderer
    networks:
      - finance

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb:0.4.18
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for sella map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
    - finance

  tcib-peer0-tcib:
    hostname: tcib-peer0-tcib
    image: hyperledger/fabric-peer:1.4.6
    environment:
      - PEER_HOST=tcib-peer0-tcib
      - PEER_NAME=tcib-peer0-tcib
      - CORE_PEER_ID=tcib-peer0-tcib
      - CORE_PEER_LOCALMSPID=tcibMSP
      - CORE_PEER_ADDRESS=tcib-peer0-tcib:7051
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=tcib_finance
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=tcib-peer0-tcib:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      # The following setting skips the gossip handshake since we are
      # are not doing mutual TLS
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      # -- About Couch --
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./artifacts/crypto-config/peerOrganizations/tcib/peers/peer0.tcib/:/etc/hyperledger/crypto/peer
    depends_on:
      - couchdb1
    networks:
      - finance
